@startuml Object Diagram

object User {
    username = "Lorin"
    bio = "I'm a software engineer"
    password = "Password"
    postsCount = null
    followersCount = null
    followingCount = null
    pictures = null
}  

object SignInUI {
    WIDTH = 300
    HEIGHT = 500

}

@enduml