@startuml SingUpIn Sequence Diagram

participant SingInUI as SI
participant SingUpUI as SU

activate SI
SI -> SU: Register Now
destroy SI

activate SU
SU --> SU: Verify Username
SU --> SU: Create User
SU -> SI: Sign In
destroy SU

activate SI
destroy SI

@enduml